name: Prod deploy

on:
  push:
    branches: [main]

jobs:
  - name: 👀 Read app name
    uses: SebRollen/toml-action@v1.0.0
    id: app_name
    with:
      file: "fly.toml"
      field: "app"

  - name: 🚀 Deploy Staging
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses: superfly/flyctl-actions@1.3
    with:
      args: "deploy --app ${{ steps.app_name.outputs.value }}-staging --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  - name: 🚀 Deploy Production
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: superfly/flyctl-actions@1.3
    with:
      args: "deploy --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
